# exclude: updateversion.js // TODO: for some reason this also excludes the js folder...

markdown: redcarpet

exclude: [node_modules, coverage]

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
